# Generated by Django 5.1.4 on 2025-01-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='attempt',
            field=models.IntegerField(default=0),
        ),
    ]
