# Generated by Django 5.1.4 on 2025-01-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_otp_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='is_varified',
            field=models.BooleanField(default=False),
        ),
    ]
